// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteKeywordTrendExplorer(arg1) {
  return window['go']['keyword_trend_explorer']['Service']['DeleteKeywordTrendExplorer'](arg1);
}

export function GetKeywordTrendExplorer(arg1) {
  return window['go']['keyword_trend_explorer']['Service']['GetKeywordTrendExplorer'](arg1);
}

export function GetKeywordTrendExplorers(arg1) {
  return window['go']['keyword_trend_explorer']['Service']['GetKeywordTrendExplorers'](arg1);
}

export function GetKeywordsByExplorers(arg1, arg2) {
  return window['go']['keyword_trend_explorer']['Service']['GetKeywordsByExplorers'](arg1, arg2);
}

export function KeywordTrendExplorerRequest(arg1) {
  return window['go']['keyword_trend_explorer']['Service']['KeywordTrendExplorerRequest'](arg1);
}
