// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {file} from '../models';

export function CopyFile(arg1:string,arg2:string):Promise<void>;

export function DeleteFile(arg1:string):Promise<void>;

export function FileExists(arg1:string):Promise<boolean>;

export function ListDirFiles(arg1:string):Promise<Array<file.FileInfo>>;

export function OpenFileFolder(arg1:string,arg2:boolean):Promise<void>;

export function OpenSaveFileDialog(arg1:string,arg2:string,arg3:string):Promise<string>;

export function OpenSaveFileDialogBytes(arg1:string,arg2:string,arg3:Array<number>):Promise<string>;

export function ReadFileInfo(arg1:string):Promise<file.FileInfo>;

export function ReadJson(arg1:string):Promise<any>;

export function SaveJson(arg1:string,arg2:any):Promise<void>;
