// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CopyFile(arg1, arg2) {
  return window['go']['file']['Service']['CopyFile'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['file']['Service']['DeleteFile'](arg1);
}

export function FileExists(arg1) {
  return window['go']['file']['Service']['FileExists'](arg1);
}

export function ListDirFiles(arg1) {
  return window['go']['file']['Service']['ListDirFiles'](arg1);
}

export function OpenFileFolder(arg1, arg2) {
  return window['go']['file']['Service']['OpenFileFolder'](arg1, arg2);
}

export function OpenSaveFileDialog(arg1, arg2, arg3) {
  return window['go']['file']['Service']['OpenSaveFileDialog'](arg1, arg2, arg3);
}

export function OpenSaveFileDialogBytes(arg1, arg2, arg3) {
  return window['go']['file']['Service']['OpenSaveFileDialogBytes'](arg1, arg2, arg3);
}

export function ReadFileInfo(arg1) {
  return window['go']['file']['Service']['ReadFileInfo'](arg1);
}

export function ReadJson(arg1) {
  return window['go']['file']['Service']['ReadJson'](arg1);
}

export function SaveJson(arg1, arg2) {
  return window['go']['file']['Service']['SaveJson'](arg1, arg2);
}
