// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {resp} from '../models';

export function CheckAndGetLatestServerVersion():Promise<resp.Response>;

export function DoUpgrade():Promise<resp.Response>;

export function GetDownloadUrlInfo(arg1:string):Promise<resp.Response>;

export function RestartApplication(arg1:string):Promise<resp.Response>;
