// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckAndGetLatestServerVersion() {
  return window['go']['version']['Service']['CheckAndGetLatestServerVersion']();
}

export function DoUpgrade() {
  return window['go']['version']['Service']['DoUpgrade']();
}

export function GetDownloadUrlInfo(arg1) {
  return window['go']['version']['Service']['GetDownloadUrlInfo'](arg1);
}

export function RestartApplication(arg1) {
  return window['go']['version']['Service']['RestartApplication'](arg1);
}
