// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteKeyword(arg1) {
  return window['go']['keyword']['Service']['DeleteKeyword'](arg1);
}

export function GetKeywordsByExplorers(arg1) {
  return window['go']['keyword']['Service']['GetKeywordsByExplorers'](arg1);
}
