// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {resp} from '../models';

export function DeleteKeyword(arg1:number):Promise<resp.Response>;

export function GetKeywordsByExplorers(arg1:number):Promise<resp.Response>;
