// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['command']['Service']['Greet'](arg1);
}

export function ProgressTracker() {
  return window['go']['command']['Service']['ProgressTracker']();
}
