// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {resp} from '../models';

export function FeedBack(arg1:models.FeedBack):Promise<resp.Response>;

export function Fullscreen():Promise<void>;

export function GetFeedBackUrl(arg1:models.FeedbackReq):Promise<resp.Response>;

export function GetGeneralInfo():Promise<resp.Response>;

export function GetGithubReleaseList():Promise<resp.Response>;

export function Hide():Promise<void>;

export function IsWindows():Promise<boolean>;

export function Minimise():Promise<void>;

export function NormalScreen():Promise<void>;

export function Quit():Promise<void>;

export function ReloadApp():Promise<void>;

export function SetGeneralData(arg1:models.Setting):Promise<resp.Response>;
