// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FeedBack(arg1) {
  return window['go']['setting']['Service']['FeedBack'](arg1);
}

export function Fullscreen() {
  return window['go']['setting']['Service']['Fullscreen']();
}

export function GetFeedBackUrl(arg1) {
  return window['go']['setting']['Service']['GetFeedBackUrl'](arg1);
}

export function GetGeneralInfo() {
  return window['go']['setting']['Service']['GetGeneralInfo']();
}

export function GetGithubReleaseList() {
  return window['go']['setting']['Service']['GetGithubReleaseList']();
}

export function Hide() {
  return window['go']['setting']['Service']['Hide']();
}

export function IsWindows() {
  return window['go']['setting']['Service']['IsWindows']();
}

export function Minimise() {
  return window['go']['setting']['Service']['Minimise']();
}

export function NormalScreen() {
  return window['go']['setting']['Service']['NormalScreen']();
}

export function Quit() {
  return window['go']['setting']['Service']['Quit']();
}

export function ReloadApp() {
  return window['go']['setting']['Service']['ReloadApp']();
}

export function SetGeneralData(arg1) {
  return window['go']['setting']['Service']['SetGeneralData'](arg1);
}
